@extends('website.layouts.dashboard')
@section('title', $tenancy->tenantName().' | '.config('app.name'))
@section('page-title', $tenancy->tenantName())
@section('dashboard-content')
<div class="mx-auto max-w-5xl space-y-6">
    <section class="rounded-2xl border border-slate-200 bg-white p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div class="min-w-0"><p class="text-sm text-slate-500">{{ $tenancy->listing?->title }}@if ($tenancy->unit) &middot; {{ __('Unit :name', ['name' => $tenancy->unit->name]) }} @endif</p><h2 class="mt-1 text-lg font-bold">{{ $tenancy->tenantName() }}</h2><p class="break-words text-sm text-slate-500">{{ $tenancy->tenant_phone }} {{ $tenancy->tenant_email }}</p></div><div class="flex shrink-0 gap-2"><a href="{{ route('owner.rent-management.tenancies.edit', $tenancy) }}" class="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700">{{ __('Edit') }}</a><form action="{{ route('owner.rent-management.tenancies.destroy', $tenancy) }}" method="POST" onsubmit="return confirm('{{ __('Remove this tenancy?') }}')">@csrf @method('DELETE')<button class="rounded-lg border border-red-200 px-4 py-2 text-sm font-semibold text-red-600" type="submit">{{ __('Remove') }}</button></form></div></div><div class="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><div><span class="block text-xs text-slate-500">{{ __('Rent') }}</span>{{ money($tenancy->rent_amount) }}{{ __('/mo') }}</div><div><span class="block text-xs text-slate-500">{{ __('Deposit') }}</span>{{ money($tenancy->deposit_amount) }}</div><div><span class="block text-xs text-slate-500">{{ __('Start date') }}</span>{{ $tenancy->start_date->format('M j, Y') }}</div><div><span class="block text-xs text-slate-500">{{ __('Status') }}</span>{{ __(ucfirst($tenancy->status)) }}</div></div></section>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="flex items-center justify-between p-5"><h2 class="font-bold">{{ __('Rent payments') }}</h2></div><div class="divide-y">@forelse ($rentPayments as $payment)<div class="flex flex-wrap items-center justify-between gap-3 px-5 py-3 text-sm"><div><p class="font-semibold">{{ money($payment->amount) }} &middot; {{ __('due :date', ['date' => $payment->due_date->format('M j, Y')]) }}</p><span class="rounded-full px-2 py-0.5 text-xs font-semibold {{ match($payment->status) { 'paid' => 'bg-emerald-50 text-emerald-700', 'overdue' => 'bg-red-50 text-red-700', default => 'bg-slate-100 text-slate-600' } }}">{{ __(ucfirst($payment->status)) }}</span>@if ($payment->receipt)<span class="ml-2 text-xs text-slate-500">{{ __('Receipt :number', ['number' => $payment->receipt->receipt_number]) }}</span>@endif</div>@if ($payment->status !== 'paid')<form action="{{ route('owner.rent-management.rent-payments.mark-paid', $payment) }}" method="POST">@csrf<button class="rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-semibold text-white" type="submit">{{ __('Mark paid') }}</button></form>@endif</div>@empty<p class="p-5 text-sm text-slate-500">{{ __('No rent payments recorded yet.') }}</p>@endforelse</div><form class="grid grid-cols-1 gap-3 border-t p-5 sm:grid-cols-4" action="{{ route('owner.rent-management.tenancies.rent-payments.store', $tenancy) }}" method="POST">
        @csrf
        <label class="text-xs font-semibold text-slate-600">{{ __('Period start') }}<input class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" name="period_start" type="date" required></label>
        <label class="text-xs font-semibold text-slate-600">{{ __('Period end') }}<input class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" name="period_end" type="date" required></label>
        <label class="text-xs font-semibold text-slate-600">{{ __('Due date') }}<input class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" name="due_date" type="date" required></label>
        <div class="flex items-end gap-2">
            <label class="min-w-0 flex-1 text-xs font-semibold text-slate-600">{{ __('Amount') }}<input class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" name="amount" type="number" min="0" value="{{ $tenancy->rent_amount }}" required></label>
            <button class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold" type="submit">{{ __('Add') }}</button>
        </div>
    </form></section>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><h2 class="p-5 font-bold">{{ __('Ledger entries for this tenancy') }}</h2><div class="divide-y">@forelse ($ledgerTransactions as $entry)<div class="flex justify-between gap-4 px-5 py-3 text-sm"><div class="min-w-0"><p>{{ $entry->category }}</p><time class="text-xs text-slate-500">{{ $entry->occurred_on->format('M j, Y') }}</time></div><span class="shrink-0 font-semibold {{ $entry->type === 'income' ? 'text-emerald-600' : 'text-red-600' }}">{{ $entry->type === 'income' ? '+' : '-' }}{{ money($entry->amount) }}</span></div>@empty<p class="p-5 text-sm text-slate-500">{{ __('No income/expense entries linked to this tenancy yet — record them from the') }} <a href="{{ route('owner.rent-management.ledger.index') }}" class="font-semibold text-indigo-600">{{ __('ledger') }}</a>.</p>@endforelse</div></section>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><h2 class="p-5 font-bold">{{ __('Agreements') }}</h2><div class="divide-y">@forelse ($agreements as $agreement)<div class="flex items-center justify-between gap-3 px-5 py-3 text-sm"><span class="min-w-0">{{ __('Generated :date', ['date' => $agreement->generated_at->format('M j, Y')]) }}</span><a href="{{ route('owner.rent-management.agreements.show', $agreement) }}" class="shrink-0 font-semibold text-indigo-600">{{ __('View') }}</a></div>@empty<p class="p-5 text-sm text-slate-500">{{ __('No agreements generated yet.') }}</p>@endforelse</div>@if ($templates->isNotEmpty())<form class="flex flex-wrap items-center gap-2 border-t p-5" action="{{ route('owner.rent-management.agreements.generate') }}" method="POST">@csrf<input type="hidden" name="tenancy_id" value="{{ $tenancy->id }}"><select class="w-full min-w-0 rounded-lg border border-slate-200 px-3 py-2 text-sm sm:w-auto" name="agreement_template_id"><option value="">{{ __('Default template') }}</option>@foreach ($templates as $template)<option value="{{ $template->id }}">{{ $template->name }}</option>@endforeach</select><button class="w-full rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white sm:w-auto" type="submit">{{ __('Generate agreement') }}</button></form>@else<p class="border-t p-5 text-sm text-slate-500">{{ __('Create an') }} <a href="{{ route('owner.rent-management.agreements.index') }}" class="font-semibold text-indigo-600">{{ __('agreement template') }}</a> {{ __('to generate documents.') }}</p>@endif</section>
</div>
@endsection
