<?php

namespace App\Support;

/**
 * English defaults for the message groups Laravel's own internals resolve
 * directly (validation rules, auth guard, password broker, paginator) — the
 * framework calls `trans('validation.required')` etc. by hardcoded convention,
 * so these groups must keep existing, but the actual text is not duplicated
 * here as a separate file-based language: every leaf value below is itself a
 * lookup key into `lang/en.json` / `lang/bn.json` via
 * {@see DatabaseTranslationLoader}, keeping one single source of translated text.
 */
class FrameworkLanguageLines
{
    /**
     * @return array<string, array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            'auth' => static::auth(),
            'passwords' => static::passwords(),
            'pagination' => static::pagination(),
            'validation' => static::validation(),
        ];
    }

    /**
     * @return array<string, string>
     */
    public static function auth(): array
    {
        return [
            'failed' => 'These credentials do not match our records.',
            'password' => 'The provided password is incorrect.',
            'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
        ];
    }

    /**
     * @return array<string, string>
     */
    public static function passwords(): array
    {
        return [
            'reset' => 'Your password has been reset.',
            'sent' => 'We have emailed your password reset link.',
            'throttled' => 'Please wait before retrying.',
            'token' => 'This password reset token is invalid.',
            'user' => "We can't find a user with that email address.",
        ];
    }

    /**
     * @return array<string, string>
     */
    public static function pagination(): array
    {
        return [
            'previous' => '&laquo; Previous',
            'next' => 'Next &raquo;',
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public static function validation(): array
    {
        return [
            'accepted' => 'The :attribute field must be accepted.',
            'accepted_if' => 'The :attribute field must be accepted when :other is :value.',
            'active_url' => 'The :attribute field must be a valid URL.',
            'after' => 'The :attribute must be later than :date.',
            'after_or_equal' => 'The :attribute field must be a date after or equal to :date.',
            'alpha' => 'The :attribute field must only contain letters.',
            'alpha_dash' => 'The :attribute field must only contain letters, numbers, dashes, and underscores.',
            'alpha_num' => 'The :attribute field must only contain letters and numbers.',
            'any_of' => 'The :attribute field is invalid.',
            'array' => 'The :attribute format is invalid.',
            'ascii' => 'The :attribute field must only contain single-byte alphanumeric characters and symbols.',
            'before' => 'The :attribute must be earlier than :date.',
            'before_or_equal' => 'The :attribute field must be a date before or equal to :date.',
            'between' => [
                'array' => 'The :attribute field must have between :min and :max items.',
                'file' => 'The :attribute field must be between :min and :max kilobytes.',
                'numeric' => 'The :attribute field must be between :min and :max.',
                'string' => 'The :attribute field must be between :min and :max characters.',
            ],
            'boolean' => 'Please select a valid option for the :attribute.',
            'can' => 'The :attribute field contains an unauthorized value.',
            'confirmed' => 'The :attribute and its confirmation do not match.',
            'contains' => 'The :attribute field is missing a required value.',
            'current_password' => 'The password is incorrect.',
            'date' => 'Please enter a valid :attribute.',
            'date_equals' => 'The :attribute field must be a date equal to :date.',
            'date_format' => 'The :attribute field must match the format :format.',
            'decimal' => 'The :attribute field must have :decimal decimal places.',
            'declined' => 'The :attribute field must be declined.',
            'declined_if' => 'The :attribute field must be declined when :other is :value.',
            'different' => 'The :attribute field and :other must be different.',
            'digits' => 'The :attribute field must be :digits digits.',
            'digits_between' => 'The :attribute field must be between :min and :max digits.',
            'dimensions' => 'The :attribute field has invalid image dimensions.',
            'distinct' => 'The :attribute field has a duplicate value.',
            'doesnt_contain' => 'The :attribute field must not contain any of the following: :values.',
            'doesnt_end_with' => 'The :attribute field must not end with one of the following: :values.',
            'doesnt_start_with' => 'The :attribute field must not start with one of the following: :values.',
            'email' => 'Please enter a valid :attribute, like name@example.com.',
            'encoding' => 'The :attribute field must be encoded in :encoding.',
            'ends_with' => 'The :attribute field must end with one of the following: :values.',
            'enum' => 'The selected :attribute is invalid.',
            'exists' => 'The selected :attribute no longer exists. Please pick another.',
            'extensions' => 'The :attribute field must have one of the following extensions: :values.',
            'file' => 'The :attribute field must be a file.',
            'filled' => 'The :attribute field must have a value.',
            'gt' => [
                'array' => 'The :attribute field must have more than :value items.',
                'file' => 'The :attribute field must be greater than :value kilobytes.',
                'numeric' => 'The :attribute field must be greater than :value.',
                'string' => 'The :attribute field must be greater than :value characters.',
            ],
            'gte' => [
                'array' => 'The :attribute field must have :value items or more.',
                'file' => 'The :attribute field must be greater than or equal to :value kilobytes.',
                'numeric' => 'The :attribute field must be greater than or equal to :value.',
                'string' => 'The :attribute field must be greater than or equal to :value characters.',
            ],
            'hex_color' => 'The :attribute field must be a valid hexadecimal color.',
            'image' => 'The :attribute must be an image file (JPG, PNG, GIF or WEBP).',
            'in' => 'Please choose a valid :attribute from the list.',
            'in_array' => 'The :attribute field must exist in :other.',
            'in_array_keys' => 'The :attribute field must contain at least one of the following keys: :values.',
            'integer' => 'The :attribute must be a whole number.',
            'ip' => 'The :attribute field must be a valid IP address.',
            'ipv4' => 'The :attribute field must be a valid IPv4 address.',
            'ipv6' => 'The :attribute field must be a valid IPv6 address.',
            'json' => 'The :attribute must be valid JSON.',
            'list' => 'The :attribute field must be a list.',
            'lowercase' => 'The :attribute field must be lowercase.',
            'lt' => [
                'array' => 'The :attribute field must have less than :value items.',
                'file' => 'The :attribute field must be less than :value kilobytes.',
                'numeric' => 'The :attribute field must be less than :value.',
                'string' => 'The :attribute field must be less than :value characters.',
            ],
            'lte' => [
                'array' => 'The :attribute field must not have more than :value items.',
                'file' => 'The :attribute field must be less than or equal to :value kilobytes.',
                'numeric' => 'The :attribute field must be less than or equal to :value.',
                'string' => 'The :attribute field must be less than or equal to :value characters.',
            ],
            'mac_address' => 'The :attribute field must be a valid MAC address.',
            'max' => [
                'array' => 'Please select no more than :max :attribute.',
                'file' => 'The :attribute must be :max kilobytes or smaller.',
                'numeric' => 'The :attribute cannot be greater than :max.',
                'string' => 'The :attribute cannot be longer than :max characters.',
            ],
            'max_digits' => 'The :attribute field must not have more than :max digits.',
            'mimes' => 'The :attribute field must be a file of type: :values.',
            'mimetypes' => 'The :attribute field must be a file of type: :values.',
            'min' => [
                'array' => 'Please select at least :min :attribute.',
                'file' => 'The :attribute must be at least :min kilobytes.',
                'numeric' => 'The :attribute must be at least :min.',
                'string' => 'The :attribute must be at least :min characters long.',
            ],
            'min_digits' => 'The :attribute field must have at least :min digits.',
            'missing' => 'The :attribute field must be missing.',
            'missing_if' => 'The :attribute field must be missing when :other is :value.',
            'missing_unless' => 'The :attribute field must be missing unless :other is :value.',
            'missing_with' => 'The :attribute field must be missing when :values is present.',
            'missing_with_all' => 'The :attribute field must be missing when :values are present.',
            'multiple_of' => 'The :attribute field must be a multiple of :value.',
            'not_in' => 'The selected :attribute is invalid.',
            'not_regex' => 'The :attribute field format is invalid.',
            'numeric' => 'The :attribute must be a number.',
            'password' => [
                'letters' => 'The :attribute field must contain at least one letter.',
                'mixed' => 'The :attribute field must contain at least one uppercase and one lowercase letter.',
                'numbers' => 'The :attribute field must contain at least one number.',
                'symbols' => 'The :attribute field must contain at least one symbol.',
                'uncompromised' => 'The given :attribute has appeared in a data leak. Please choose a different :attribute.',
            ],
            'present' => 'The :attribute field must be present.',
            'present_if' => 'The :attribute field must be present when :other is :value.',
            'present_unless' => 'The :attribute field must be present unless :other is :value.',
            'present_with' => 'The :attribute field must be present when :values is present.',
            'present_with_all' => 'The :attribute field must be present when :values are present.',
            'prohibited' => 'The :attribute field is prohibited.',
            'prohibited_if' => 'The :attribute field is prohibited when :other is :value.',
            'prohibited_if_accepted' => 'The :attribute field is prohibited when :other is accepted.',
            'prohibited_if_declined' => 'The :attribute field is prohibited when :other is declined.',
            'prohibited_unless' => 'The :attribute field is prohibited unless :other is in :values.',
            'prohibits' => 'The :attribute field prohibits :other from being present.',
            'regex' => 'The :attribute field format is invalid.',
            'required' => 'Please enter the :attribute.',
            'required_array_keys' => 'The :attribute field must contain entries for: :values.',
            'required_if' => 'Please enter the :attribute when :other is :value.',
            'required_if_accepted' => 'The :attribute field is required when :other is accepted.',
            'required_if_declined' => 'The :attribute field is required when :other is declined.',
            'required_unless' => 'The :attribute field is required unless :other is in :values.',
            'required_with' => 'The :attribute field is required when :values is present.',
            'required_with_all' => 'The :attribute field is required when :values are present.',
            'required_without' => 'The :attribute field is required when :values is not present.',
            'required_without_all' => 'The :attribute field is required when none of :values are present.',
            'same' => 'The :attribute field must match :other.',
            'size' => [
                'array' => 'The :attribute field must contain :size items.',
                'file' => 'The :attribute field must be :size kilobytes.',
                'numeric' => 'The :attribute field must be :size.',
                'string' => 'The :attribute field must be :size characters.',
            ],
            'starts_with' => 'The :attribute field must start with one of the following: :values.',
            'string' => 'The :attribute must be text.',
            'timezone' => 'The :attribute field must be a valid timezone.',
            'unique' => 'This :attribute is already in use. Please choose a different one.',
            'uploaded' => 'The :attribute could not be uploaded. Please try again with a smaller file.',
            'uppercase' => 'The :attribute field must be uppercase.',
            'url' => 'Please enter a valid :attribute, starting with http:// or https://.',
            'ulid' => 'The :attribute field must be a valid ULID.',
            'uuid' => 'The :attribute field must be a valid UUID.',

            'custom' => [
                'attribute-name' => [
                    'rule-name' => 'custom-message',
                ],
            ],

            'attributes' => [
                'account_ref' => 'account reference',
                'action' => 'action',
                'additional_meta' => 'additional meta',
                'address' => 'address',
                'admin_note' => 'admin note',
                'advance_months' => 'advance months',
                'agreed_amount' => 'agreed amount',
                'allowed_for' => 'tenant type',
                'amount' => 'amount',
                'answer' => 'answer',
                'app_store_url' => 'App Store URL',
                'applicable_for' => 'applicable for',
                'area_sqft' => 'area (sqft)',
                'assigned_to' => 'assignee',
                'auto_renew' => 'auto renew',
                'available_time' => 'available time',
                'avatar' => 'avatar',
                'bathrooms' => 'bathrooms',
                'bedrooms' => 'bedrooms',
                'bio' => 'bio',
                'blog_category_id' => 'blog category',
                'body' => 'body',
                'branding' => 'branding',
                'category' => 'category',
                'channel' => 'channel',
                'code' => 'code',
                'commission_rate' => 'commission rate',
                'completion_date' => 'completion date',
                'content' => 'content',
                'cover_image' => 'cover image',
                'csv_file' => 'CSV file',
                'currency' => 'currency',
                'custom_fields' => 'custom fields',
                'dark_mode_default' => 'default dark mode',
                'days' => 'days',
                'decimal_places' => 'decimal places',
                'decimal_separator' => 'decimal separator',
                'default_currency' => 'default currency',
                'default_language' => 'default language',
                'description' => 'description',
                'developer_name' => 'developer name',
                'direction' => 'text direction',
                'display_name' => 'display name',
                'duration_days' => 'duration (days)',
                'email' => 'email address',
                'email_template_id' => 'email template',
                'ends_at' => 'end date',
                'excerpt' => 'excerpt',
                'exchange_rate' => 'exchange rate',
                'experience_years' => 'years of experience',
                'expires_at' => 'expiry date',
                'featured_image' => 'featured image',
                'features' => 'features',
                'firebase_service_account' => 'Firebase service account',
                'floor' => 'floor',
                'free_post_limit' => 'free post limit',
                'from' => 'start date',
                'furnished' => 'furnished',
                'gateway' => 'payment gateway',
                'general' => 'general settings',
                'group' => 'group',
                'guard_name' => 'guard name',
                'headline' => 'headline',
                'hourly_rate' => 'hourly rate',
                'icon' => 'icon',
                'ids' => 'selected items',
                'image' => 'image',
                'images' => 'images',
                'is_active' => 'active status',
                'is_available' => 'availability',
                'is_blocked' => 'blocked status',
                'is_default' => 'default flag',
                'is_featured' => 'featured flag',
                'is_filterable' => 'filterable flag',
                'is_required' => 'required flag',
                'is_urgent' => 'urgent flag',
                'is_verified' => 'verified flag',
                'key' => 'key',
                'label' => 'label',
                'language_id' => 'language',
                'language_tag' => 'language',
                'lat' => 'latitude',
                'limit_count_rule' => 'limit rule',
                'limits' => 'limits',
                'link' => 'link',
                'lng' => 'longitude',
                'localization' => 'localization',
                'max_discount' => 'maximum discount',
                'max_referrals' => 'maximum referrals',
                'max_uses' => 'maximum uses',
                'max_uses_per_user' => 'maximum uses per user',
                'meta_description' => 'meta description',
                'meta_title' => 'meta title',
                'min_order' => 'minimum order',
                'min_purchase_amount' => 'minimum purchase amount',
                'name' => 'name',
                'names' => 'names',
                'native_name' => 'native name',
                'note' => 'note',
                'og_description' => 'Open Graph description',
                'og_image' => 'Open Graph image',
                'og_title' => 'Open Graph title',
                'options' => 'options',
                'otp_driver' => 'OTP driver',
                'outcome' => 'outcome',
                'owner_email' => 'owner email',
                'owner_id' => 'owner',
                'parent_id' => 'parent',
                'parking' => 'parking',
                'password' => 'password',
                'payment_id' => 'payment',
                'permissions' => 'permissions',
                'phone' => 'phone number',
                'play_store_url' => 'Play Store URL',
                'position' => 'position',
                'post_limit' => 'post limit',
                'post_quota' => 'post quota',
                'preferences' => 'preferences',
                'price' => 'price',
                'price_from' => 'starting price',
                'primary_color' => 'primary colour',
                'priority' => 'priority',
                'project_category_id' => 'project category',
                'property_type' => 'property type',
                'question' => 'question',
                'quote' => 'quote',
                'rating' => 'rating',
                'reason' => 'reason',
                'refund_amount' => 'refund amount',
                'resolution' => 'resolution',
                'reward_description' => 'reward description',
                'reward_type' => 'reward type',
                'reward_value' => 'reward value',
                'role' => 'role',
                'role_id' => 'role',
                'saved_search_alert_enabled' => 'saved search alerts',
                'scheduled_at' => 'scheduled time',
                'secondary_color' => 'secondary colour',
                'segments' => 'segments',
                'seoable_id' => 'target record',
                'seoable_type' => 'target type',
                'service_charge' => 'service charge',
                'site_address' => 'site address',
                'site_email' => 'site email',
                'site_name' => 'site name',
                'site_phone' => 'site phone',
                'skills' => 'skills',
                'slug' => 'slug',
                'sms' => 'SMS settings',
                'social' => 'social settings',
                'social_facebook' => 'Facebook URL',
                'social_instagram' => 'Instagram URL',
                'social_twitter' => 'Twitter URL',
                'social_youtube' => 'YouTube URL',
                'sort_order' => 'sort order',
                'starts_at' => 'start date',
                'status' => 'status',
                'statuses' => 'statuses',
                'subheadline' => 'subheadline',
                'subject' => 'subject',
                'subscription_plan_id' => 'subscription plan',
                'symbol' => 'symbol',
                'symbol_position' => 'symbol position',
                'tags' => 'tags',
                'target_segments' => 'target segments',
                'technician_category_id' => 'technician category',
                'technician_id' => 'technician',
                'thousands_separator' => 'thousands separator',
                'title' => 'title',
                'to' => 'end date',
                'token' => 'token',
                'total_floors' => 'total floors',
                'twilio_from' => 'Twilio sender',
                'twilio_sid' => 'Twilio SID',
                'twilio_token' => 'Twilio token',
                'type' => 'type',
                'unlocked_features' => 'unlocked features',
                'user_email' => 'user email',
                'user_id' => 'user',
                'valid_until' => 'valid until',
                'value' => 'value',
                'verification_status' => 'verification status',
                'videos' => 'videos',
                'vonage_api_key' => 'Vonage API key',
                'vonage_api_secret' => 'Vonage API secret',
                'vonage_from' => 'Vonage sender',
                'website' => 'website',
                'whatsapp' => 'WhatsApp number',
                'zone_id' => 'zone',
            ],
        ];
    }
}
